"""Robustness scorecard: detector x attack x defense evasion rates over a corpus.

A single-message demo is an anecdote; a rate over a corpus is a claim. This script
runs each detector against every character attack on a set of fraud lures and
reports, for each cell, the **evasion rate** — of the lures a detector caught clean,
what fraction slip below threshold after the attack. It reports that rate twice: on
the raw attacked text, and after the ``normalize`` defense folds the text back to
ASCII. The gap between the two columns is the whole point:

    homoglyph / zero-width  -> normalization drives evasion to ~0 (lossless reversal)
    leet                    -> mostly recovered; a residue survives the 1=i/l ambiguity
    whitespace              -> unchanged; word-splitting can't be reversed safely

Only the always-on detectors and dependency-free character attacks run by default,
so the scorecard is fully reproducible with no keys. Point ``--data`` at a larger
corpus (e.g. LureBench's ``data/full/core/test.jsonl``) for headline numbers.

    python scripts/robustness_scorecard.py                       # bundled sample
    python scripts/robustness_scorecard.py --data <corpus.jsonl> --out-md SCORECARD.md \
        --out-png docs/assets/scorecard.png
"""

from __future__ import annotations

import argparse
import json
import os
from typing import List

from lurebench.attacks import get_attack

from lurescope.defense import normalize
from lurescope.service import _as_lure, _detector

DEFAULT_DATA = os.path.join(
    os.path.dirname(__file__), "..", "lurescope", "data", "sample_lures.jsonl"
)
DEFAULT_DETECTORS = ["tfidf-logreg", "heuristic-v0"]
DEFAULT_ATTACKS = ["homoglyph", "leet", "zero-width", "whitespace"]


def load_fraud_lures(path: str, limit: int = 0) -> List[str]:
    """Read a LureBench JSONL corpus and return the text of the fraud lures (label 1).

    Lines that are blank or begin with ``//`` (sample-shard comments) are skipped.
    """
    out = []
    with open(path, encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("//"):
                continue
            rec = json.loads(line)
            if rec.get("label") == 1:
                out.append(rec["text"])
            if limit and len(out) >= limit:
                break
    return out


def _scorer(detector_name: str):
    det = _detector(detector_name)

    def sc(text: str) -> float:
        p = det.score(_as_lure(text))
        return 0.0 if p is None else float(p)

    return sc


def compute(detectors, attacks, lures, threshold=0.5) -> dict:
    """Return the scorecard as a nested dict keyed by detector then attack."""
    built = {a: get_attack(a) for a in attacks}
    card = {"threshold": threshold, "n_fraud": len(lures), "detectors": {}}
    for dname in detectors:
        sc = _scorer(dname)
        clean = [sc(t) for t in lures]
        caught = [i for i, p in enumerate(clean) if p >= threshold]
        n = len(caught)
        row = {"clean_recall": (n / len(lures)) if lures else 0.0, "n_caught": n, "attacks": {}}
        for a in attacks:
            raw = defended = 0
            for i in caught:
                attacked = built[a].apply(lures[i])
                if sc(attacked) < threshold:
                    raw += 1
                if sc(normalize(attacked)) < threshold:
                    defended += 1
            row["attacks"][a] = {
                "evasion_raw": (raw / n) if n else 0.0,
                "evasion_normalized": (defended / n) if n else 0.0,
            }
        card["detectors"][dname] = row
    return card


def to_markdown(card: dict, corpus_label: str) -> str:
    attacks = list(next(iter(card["detectors"].values()))["attacks"])
    cols = " | ".join(f"{a} (raw → +norm)" for a in attacks)
    header = "| Detector | Clean recall | " + cols + " |"
    sep = "|" + "---|" * (2 + len(attacks))
    lines = [
        "# Robustness scorecard",
        "",
        f"Evasion rate = of the fraud lures a detector caught on clean text, the fraction "
        f"that slip below the {card['threshold']:.2f} threshold after the attack. Lower is "
        f"more robust. `+norm` re-scores the attacked text after the `normalize` defense.",
        "",
        f"**Corpus:** {corpus_label} · {card['n_fraud']} fraud lures · "
        f"generated by `scripts/robustness_scorecard.py`.",
        "",
        header,
        sep,
    ]
    for dname, row in card["detectors"].items():
        cells = [f"`{dname}`", f"{row['clean_recall']:.0%} ({row['n_caught']})"]
        for a in attacks:
            e = row["attacks"][a]
            cells.append(f"{e['evasion_raw']:.0%} → **{e['evasion_normalized']:.0%}**")
        lines.append("| " + " | ".join(cells) + " |")
    lines += [
        "",
        "Read the pattern, not the individual numbers: normalization collapses the "
        "`homoglyph` and `zero-width` columns to near zero (it reverses them losslessly), "
        "leaves a small `leet` residue (the `1`=`i`/`l` ambiguity), and does nothing for "
        "`whitespace` or a semantic paraphrase — because those can't be undone without "
        "corrupting legitimate text. The residual robustness gap is semantic, not typographic.",
        "",
    ]
    return "\n".join(lines)


def to_png(card: dict, path: str, corpus_label: str) -> bool:
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        from matplotlib.colors import LinearSegmentedColormap
    except ImportError:
        return False

    attacks = list(next(iter(card["detectors"].values()))["attacks"])
    # Rows: each detector split into a raw row and a +normalize row.
    rows, data = [], []
    for dname, row in card["detectors"].items():
        rows.append(f"{dname}\n(raw attack)")
        data.append([row["attacks"][a]["evasion_raw"] for a in attacks])
        rows.append(f"{dname}\n(+ normalize)")
        data.append([row["attacks"][a]["evasion_normalized"] for a in attacks])

    # Sequential single-hue ramp, light -> dark (magnitude encoding; high evasion = worse).
    cmap = LinearSegmentedColormap.from_list("evasion", ["#f6f7f5", "#e5534b", "#7a1712"])
    fig, ax = plt.subplots(figsize=(1.4 * len(attacks) + 3.2, 0.72 * len(rows) + 1.6))
    im = ax.imshow(data, cmap=cmap, vmin=0.0, vmax=1.0, aspect="auto")

    ax.set_xticks(range(len(attacks)))
    ax.set_xticklabels(attacks, fontsize=11)
    ax.set_yticks(range(len(rows)))
    ax.set_yticklabels(rows, fontsize=10)
    ax.set_xlabel("attack", fontsize=11)
    for i, drow in enumerate(data):
        for j, v in enumerate(drow):
            ax.text(j, i, f"{v:.0%}", ha="center", va="center",
                    color="white" if v >= 0.45 else "#14171c", fontsize=11, fontweight="bold")
    ax.set_title(
        f"LureScope robustness — fraud-lure evasion rate\n{corpus_label} · "
        f"{card['n_fraud']} lures · lower is more robust",
        fontsize=12.5, pad=12,
    )
    cbar = fig.colorbar(im, ax=ax, fraction=0.045, pad=0.03)
    cbar.set_label("evasion rate", fontsize=10)
    fig.tight_layout()
    fig.savefig(path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    return True


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--data", default=os.path.abspath(DEFAULT_DATA), help="LureBench JSONL corpus")
    ap.add_argument("--detectors", nargs="+", default=DEFAULT_DETECTORS)
    ap.add_argument("--attacks", nargs="+", default=DEFAULT_ATTACKS)
    ap.add_argument("--threshold", type=float, default=0.5)
    ap.add_argument("--limit", type=int, default=0, help="cap number of fraud lures (0 = all)")
    ap.add_argument("--out-md", default=None, help="write the scorecard markdown here")
    ap.add_argument("--out-json", default=None, help="write the raw scorecard JSON here")
    ap.add_argument("--out-png", default=None, help="write a heatmap PNG here (needs matplotlib)")
    ap.add_argument("--label", default=None, help="corpus label for the report")
    args = ap.parse_args(argv)

    lures = load_fraud_lures(args.data, args.limit)
    if not lures:
        raise SystemExit(f"no fraud lures (label==1) found in {args.data}")
    label = args.label or os.path.basename(args.data)
    card = compute(args.detectors, args.attacks, lures, args.threshold)

    md = to_markdown(card, label)
    print(md)
    if args.out_md:
        with open(args.out_md, "w", encoding="utf-8") as fh:
            fh.write(md)
    if args.out_json:
        with open(args.out_json, "w", encoding="utf-8") as fh:
            json.dump(card, fh, indent=2)
    if args.out_png:
        if to_png(card, args.out_png, label):
            print(f"\nwrote heatmap -> {args.out_png}")
        else:
            print("\nmatplotlib not installed; skipped PNG (pip install matplotlib)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
